### ISSUE TITLE
What's FQ12?

### ISSUE THREAD

**Issue by jamesray1** [ethereum/py_pairing#6]
https://github.com/ethereum/py_pairing/blob/master/py_ecc/bn128/bn128_field_elements.py
```
# The modulus of the polynomial in this representation of FQ12
FQ12_modulus_coeffs = [82, 0, 0, 0, 0, 0, -18, 0, 0, 0, 0, 0] # Implied + [1]
```

What's FQ12?

**Comment by jamesray1** [comment]
http://www.skidmore.edu/fq12/

**Comment by jamesray1** [comment]
I assume it's a finite field with 12 elements.

**Comment by alexpArtos** [comment]
It is the field underlying the target group of the pairing. The pairing is a function e(G1 x G2) --> GT.
FQ12 is an extension field of FQ with 12 dimensions (not 12 elements). 

You can look at these as coefficients over powers of a free variable (as in a polynomial), so for example, the number [a,0,...,0] would just be a scalar. Then, [a,b,c,0...0] would be 
a + bw + cw^2

Normal multiplication rules for polynomials apply:

[a,b,0...0] * [0,x,0,y,0...0] = 

(a + bw) * (xw + yw^3) = axw + ayw^3 + bxw^2 + byw^4 or in coefficient notation:
[0,ax,0,ay,0...0] + [0,0,bx,0,by,0....0] = [0,ax,bx,ay,by,0...0]

**Comment by jamesray1** [comment]
Thanks!
